exports.up = function (knex) {
  return knex.schema
    .createTable("users", function (table) {
      table.increments("id").primary();
      table.string("first_name").notNullable();
      table.string("phone_number").notNullable();
      table.string("last_name").notNullable();
      table.string("email").notNullable().unique();
      table.string("password").notNullable();
      table.string("role").notNullable();
      table.boolean("is_active").defaultTo(false);
      table.timestamp("otpexpiresat").nullable();
      table.string("otp").nullable();
      table.timestamp("created_at").nullable();
      table.timestamp("updated_at").nullable();
      table.timestamp("deleted_at").nullable();
    })
    .createTable("operators", function (table) {
      table.increments("id").primary();
      table.integer("user_id").unsigned().references("id").inTable("users");
      table.string("first_name").notNullable();
      table.string("last_name").nullable();
      table.string("force").nullable();
      table.string("speciality").nullable();
      table.boolean("currently_employed").nullable();
      table.string("birth_date").nullable();
      table.string("address").nullable();
      table.string("mental_health_support").nullable();
      table.string("status").defaultTo("pending");
      table.timestamp("created_at").nullable();
      table.timestamp("updated_at").nullable();
      table.timestamp("deleted_at").nullable();
    })
    .createTable("concierge", function (table) {
      table.increments("id").primary();
      table.integer("user_id").unsigned().references("id").inTable("users");
      table.string("full_name").notNullable();
      table.string("phone_number").nullable();
      table.string("email").nullable();
      table.string("service_branch").nullable();
      table.string("contact_number").nullable();
      table.string("birth_date").nullable();
      table.string("how_heard_about_us").notNullable();
      table.string("why_concierge").notNullable();
      table.integer("hours_per_month").notNullable();
      table.integer("number_of_operators").notNullable();
      table.string("transition_services").notNullable();
      table.string("areas_of_support").notNullable();
      table.string("uncomfortable_topics").notNullable();
      table.string("status").defaultTo("pending");
      table.timestamp("created_at").nullable();
      table.timestamp("updated_at").nullable();
      table.timestamp("deleted_at").nullable();
    })
    .createTable("peer_ambassador", function (table) {
      table.increments("id").primary();
      table.integer("user_id").unsigned().references("id").inTable("users");
      table.string("full_name").notNullable();
      table.string("phone_number").nullable();
      table.string("email").nullable();
      table.string("service_branch").nullable();
      table.string("contact_number").nullable();
      table.string("birth_date").nullable();
      table.string("how_heard_about_us").notNullable();
      table.string("why_peer_ambassador").notNullable();
      table.integer("hours_per_month").notNullable();
      table.integer("number_of_operators").notNullable();
      table.string("transition_services").notNullable();
      table.string("areas_of_support").notNullable();
      table.string("uncomfortable_topics").notNullable();
      table.string("status").defaultTo("pending");
      table.timestamp("created_at").nullable();
      table.timestamp("updated_at").nullable();
      table.timestamp("deleted_at").nullable();
    })
    .createTable("service_partners", function (table) {
      table.increments("id").primary();
      table.integer("user_id").unsigned().references("id").inTable("users");
      table.string("organization_name").notNullable();
      table.string("phone_number").nullable();
      table.string("address").nullable();
      table.string("web_url").notNullable();
      table.string("point_of_contact_name").notNullable();
      table.string("point_of_contact_email").notNullable();
      table.string("how_heard_about_us").notNullable();
      table.string("veteran_specific_services").notNullable();
      table.string("service_provided").notNullable();
      table.string("description").notNullable();
      table.string("status").defaultTo("pending");
      table.timestamp("created_at").nullable();
      table.timestamp("updated_at").nullable();
      table.timestamp("deleted_at").nullable();
    })
    .createTable("siging_form", function (table) {
      table.increments("id").primary();
      table.integer("form_id").unsigned().notNullable();
      table.string("signed_from").notNullable();
      table.integer("user_id").unsigned();
      table.string("signed_to").notNullable();
      table
        .integer("operator_form_id")
        .unsigned()
        .references("id")
        .inTable("operators")
        .nullable();
      table
        .integer("peer_ambassador_form_id")
        .unsigned()
        .references("id")
        .inTable("peer_ambassador")
        .nullable();
      table
        .integer("concierge_form_id")
        .unsigned()
        .references("id")
        .inTable("concierge")
        .nullable();
      table
        .integer("service_partner_form_id")
        .unsigned()
        .references("id")
        .inTable("service_partners")
        .nullable();
      table.string("full_name").nullable();
      table.string("phone_number").nullable();
      table.string("email").nullable();
      table.string("service_branch").nullable();
      table.string("contact_number").nullable();
      table.string("birth_date").nullable();
      table.string("how_heard_about_us").nullable();
      table.string("transition_services").nullable();
      table.string("areas_of_support").nullable();
      table.string("uncomfortable_topics").nullable();
      table.string("force").nullable();
      table.string("speciality").nullable();
      table.boolean("currently_employed").nullable();
      table.string("address").nullable();
      table.string("mental_health_support").nullable();
      table.integer("hours_per_month").nullable();
      table.integer("number_of_operators").nullable();
      table.string("why_concierge").nullable();
      table.string("why_peer_ambassador").nullable();
      table.string("organization_name").nullable();
      table.string("web_url").nullable();
      table.string("point_of_contact_name").nullable();
      table.string("point_of_contact_email").nullable();
      table.string("veteran_specific_services").nullable();
      table.string("service_provided").nullable();
      table.string("description").nullable();
      table.string("status").defaultTo("pending");
      table.timestamp("created_at").notNullable();
      table.timestamp("updated_at").nullable();
      table.timestamp("deleted_at").nullable();
    });
};

exports.down = function (knex) {
  return knex.schema
    .dropTableIfExists("siging_form")
    .dropTableIfExists("service_partners")
    .dropTableIfExists("peer_ambassador")
    .dropTableIfExists("concierge")
    .dropTableIfExists("operators")
    .dropTableIfExists("users");
};
