module.exports = Object.freeze({
  NO_CONTENT: "NO_CONTENT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  PARTIAL_CONTENT: "PARTIAL_CONTENT",
  ALREADY_EXIST: "ALREADY_EXIST",
});
